### ISSUE TITLE
ImportError: cannot import name 'convert_to_constants'

### ISSUE THREAD

**Issue by hazily123** [tensorspace-team/tensorspace#229]
在导入tensorflowjs的时候就会报这个错，在执行转换格式脚本的时候也是现实这个包导入有问题。
>>> import tensorflowjs as tfjs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\anaconda\anaconda3\lib\site-packages\tensorflowjs-1.0.1-py3.6.egg\tensorflowjs\__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "F:\anaconda\anaconda3\lib\site-packages\tensorflowjs-1.0.1-py3.6.egg\tensorflowjs\converters\__init__.py", line 24, in <module>
    from tensorflowjs.converters.tf_saved_model_conversion_v2 import convert_tf_saved_model
  File "F:\anaconda\anaconda3\lib\site-packages\tensorflowjs-1.0.1-py3.6.egg\tensorflowjs\converters\tf_saved_model_conversion_v2.py", line 29, in <module>
    from tensorflow.python.framework import convert_to_constants
ImportError: cannot import name 'convert_to_constants'

**Comment by JordanMicahBennett** [comment]
I figured out that the problem here, was that convert_to_constants.py was missing from my python tensorflow framework directory.

This problem can easily be solved, by copying the [convert_to_constants.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/convert_to_constants.py) found on the official [web-page's framework directory](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/convert_to_constants.py), into your **Python36\Lib\site-packages\tensorflow\python\framework** folder.

**Comment by syt123450** [comment]
@hazily123 看起来像是 tensorflowjs 版本问题。对于模型预处理，可以试试最新发布的 TensorSpace 预处理工具 [TensorSpace-Converter](https://github.com/tensorspace-team/tensorspace-converter)（使用这个工具来预处理，理论上不会遇到以上提到的 python 包版本问题），可以极大简化预处理过程。

**Comment by hazily123** [comment]
我把文件放进去了文件夹，但是没有任何作用，还是会报那个错误。
