### ISSUE TITLE
This is probably not a problem with npm. There is likely additional logging output above.

### ISSUE THREAD

**Issue by jiapei100** [tensorspace-team/tensorspace#237]
```console
➜  helloworld-angular git:(master) ✗ npm run start

> angular-example@0.0.0 start ....../tensorspace/examples/helloworld-angular
> ng serve

Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber.project (....../tensorspace/examples/helloworld-angular/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (....../tensorspace/examples/helloworld-angular/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (....../tensorspace/examples/helloworld-angular/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (....../tensorspace/examples/helloworld-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (....../tensorspace/examples/helloworld-angular/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (....../tensorspace/examples/helloworld-angular/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (....../tensorspace/examples/helloworld-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (....../tensorspace/examples/helloworld-angular/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (....../tensorspace/examples/helloworld-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (....../tensorspace/examples/helloworld-angular/node_modules/rxjs/internal/operators/switchMap.js:86:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-example@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-04-14T08_44_32_072Z-debug.log
```

And I tried `sudo npm run start`, but
```console
➜  helloworld-angular git:(master) ✗ sudo npm run start
sudo: npm: command not found
```

Can anybody give me a hand please?

Cheers
Pei

**Comment by Yun-Tianming** [comment]
我遇到了类似的问题，请问你解决了吗
